= Exception handling

NOTE: Исключения, с точки зрения unit-testing, представляют собой негативный сценарий выполнения, поэтому его следует тестировать отдельными тестами.

NOTE: Собственные исключения, которые используются в проекте, часто выносят в пакет `exception`. Поэтому рекомендуется использовать данную практику и в этом задании.

WARNING: Для каждого *Specification of task* необходимо создавать свои классы *Task* и *Demo*

== Specification of task 1

=== Class `Task`

* создать метод в котором объявить переменную типа `String` со значением `null`
* вызвать любой метод у этой переменной

=== Class `Demo`

* вызвать этот метод
* отловить возникшее исключение

== Specification of task 2

=== Class `Task`

* создать метод, бросающий `ArrayIndexOutOfBoundsException`

=== Class `Demo`

* вызвать этот метод
* отловить возникшее исключение

== Specification of task 3

=== Class `Task`

* создать собственный класс-исключение - наследник класса `Exception`
* создать метод, бросающий это исключение

=== Class `Demo`

* вызвать этот метод
* отловить возникшее исключение
* вывести `stack trace` в Standard Output

== Specification of task 4

=== Class `Task`

* создать собственный класс-исключение - наследник класса `RuntimeException`
* добавить в конструктор своего класса возможность указания сообщения
* создать метод, бросающий это исключение

=== Class `Demo`

* вызвать этот метод
* отловить возникшее исключение
* вывести `stack trace` в Standard Output

== Specification of task 5

=== Class `Task`

* создать метод, в котором:
** бросить одно из существующих в JDK исключений
** отловить возникшее исключение
** бросить своё собственное, указав в качестве причины сообщение отловленного исключения

=== Class `Demo`

* вызвать этот метод
* отловить возникшее исключение

== Specification of task 6

=== Class `Task`

* создать метод, который по очереди выбрасывает одно из 3-х различных исключений

=== Class `Demo`

* вызвать этот метод
* отловить и обработать возникшие исключения
** два из них имею одинаковую обработку
** обработка третьего должна отличаться от 2-х других

== Specification of task 7

=== Class `Task`

* написать метод, который бросает по очереди исключение и Runtime исключение

=== Class `Demo`

* вызвать этот метод в конструкции `try ... catch ... finally`, где перехватывать только _обычное_ исключение
* убедиться что блок `finally` отрабатывает для случая с _обычным_ исключением
